name: build

on:
    push:
        tags:
            - 'v*'
        branches:
            - '**'
        paths:
            - '**/.config'
            - '.github/workflows/build.yaml'
            - '*.sh'
            - 'clang/*.cmake'
    workflow_dispatch:

jobs:
    meta:
        uses: ./.github/workflows/meta.yml

    sysroot:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                arch: [x64, arm64]
            fail-fast: false
        
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: true

            - name: Update system
              run: |
                  sudo apt-get update
                  sudo apt-get remove --purge firefox
                  sudo apt-get upgrade

            - name: Install deps
              run: |
                  sudo apt-get install -y build-essential automake texinfo flex bison help2man libtool-bin

            - name: Install ctng
              run: |
                  ./build-ctng.sh

            - name: Build toolchain
              run: |
                  cd ${{ matrix.arch }}
                  ../install-ctng/bin/ct-ng build
                  cd ..

            - name: Package toolchain
              run: |
                  tar Jcvf maa-linux-toolchain-sysroot-${{ matrix.arch }}.tar.xz x-tools

            - name: Upload toolchain
              uses: actions/upload-artifact@v4
              with:
                  name: MaaLinuxToolchainSysroot-${{ matrix.arch }}
                  path: maa-linux-toolchain-sysroot-${{ matrix.arch }}.tar.xz

            - name: Upload logs
              uses: actions/upload-artifact@v4
              if: always()
              with:
                name: MaaLinuxToolchainLogs-${{ matrix.arch }}
                path: ${{ matrix.arch }}/build.log

    clang:
        needs: [sysroot]
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: true

            - uses: actions/download-artifact@v4
              with:
                  path: assets

            - name: Unpack sysroot
              run: |
                for pack in assets/**/*.tar.xz; do
                  tar Jvxf $pack
                done
                ls x-tools

            - name: Clone clang
              run: |
                ./clone-llvm.sh

            - name: Build clang stage1
              run: |
                ./build-clang-stage1.sh

            - name: Build libcxx stage1
              run: |
                ./build-libcxx-stage1.sh

            - name: Build clang stage2
              run: |
                ./build-clang-stage2.sh

            - name: Build libcxx stage2 x64
              run: |
                ./build-libcxx-stage2-x64.sh

            - name: Build libcxx stage2 arm64
              run: |
                ./build-libcxx-stage2-arm64.sh

            - name: Move tools
              run: |
                mv stage2 x-tools/tools

            - name: Package toolchain
              run: |
                  tar Jcvf maa-linux-toolchain.tar.xz x-tools

            - name: Upload toolchain
              uses: actions/upload-artifact@v4
              with:
                  name: MaaLinuxToolchain
                  path: maa-linux-toolchain.tar.xz

    release:
        if: ${{ needs.meta.outputs.is_release == 'true' }}
        needs: [meta, sysroot, clang]
        runs-on: ubuntu-latest
        env:
            OUTPUT_PUBLISH_FAILED: 'echo "failed=true" >> $GITHUB_OUTPUT && echo "::error::Failed to publish packages"'

        steps:
            - uses: actions/download-artifact@v4
              with:
                  path: assets

            - uses: softprops/action-gh-release@v2
              with:
                  files: assets/**/*.tar.xz
                  tag_name: ${{ needs.meta.outputs.tag }}
                  prerelease: ${{ needs.meta.outputs.is_pre_release == 'true' }}
                  generate_release_notes: true
