name: build

on:
    push:
        tags:
            - 'v*'
        branches:
            - '**'
        paths:
            - 'x64/.config'
            - 'arm64/.config'
            - '.github/workflows/build.yaml'
            - 'build-ctng.sh'
    workflow_dispatch:

jobs:
    ubuntu:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                arch: [x64, arm64]
            fail-fast: false
        
        steps:
            - name: Update system
              run: |
                  sudo apt-get update
                  sudo apt-get upgrade

            - name: Install deps
              run: |
                  sudo apt-get install -y build-essential automake texinfo flex bison

            - name: Install ctng
              run: |
                  ./build-ctng.sh

            - name: Build toolchain
              run: |
                  cd ${{ matrix.arch }}
                  install-ctng/bin/ct-ng build
                  cd ..
                  find x-tools

